[2024-08-25T16:57:47.800+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T16:57:47.806+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-25T16:57:45.181181+00:00 [queued]>
[2024-08-25T16:57:47.808+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-25T16:57:45.181181+00:00 [queued]>
[2024-08-25T16:57:47.808+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-25T16:57:47.812+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-08-25 16:57:45.181181+00:00
[2024-08-25T16:57:47.814+0000] {standard_task_runner.py:72} INFO - Started process 117 to run task
[2024-08-25T16:57:47.816+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-08-25T16:57:45.181181+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp3cwbst0a']
[2024-08-25T16:57:47.817+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask s3_upload
[2024-08-25T16:57:47.832+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-25T16:57:45.181181+00:00 [running]> on host d52e67a52229
[2024-08-25T16:57:47.852+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kittaya' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T16:57:45.181181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T16:57:45.181181+00:00'
[2024-08-25T16:57:47.853+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T16:57:48.513+0000] {logging_mixin.py:190} INFO - The AWS Access Key Id you provided does not exist in our records.
[2024-08-25T16:57:48.571+0000] {logging_mixin.py:190} INFO - Error uploading file to S3: The AWS Access Key Id you provided does not exist in our records.
[2024-08-25T16:57:48.572+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-25T16:57:48.581+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T16:57:48.581+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-08-25T16:57:45.181181+00:00, execution_date=20240825T165745, start_date=20240825T165747, end_date=20240825T165748
[2024-08-25T16:57:48.632+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T16:57:48.642+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
